exclude:
- /BaseGameUtils/src/main/java/com/google/example/games/basegameutils/.*
- /android/src/feup/lpoo/reversi/AndroidLauncher.java
- /desktop/src/feup/lpoo/reversi/desktop/DesktopLauncher.java
- /html/.*
component_depth: 6
languages:
- java
- javascript
